import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Navbar, Hero } from "../../components/index";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Crypt captivating</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <main className="">
        {/* Navbar section */}
        <div className="bg-slate-700">
          <Navbar />
        </div>
        {/* Hero section */}
        <div className="bg-slate-800">
          <Hero />
        </div>
        {/* Pricing */}
        {/* Description */}
        {/* Footer */}
      </main>
    </>
  );
}
